/// <reference types="cypress" />

describe("E2E - Testing Main Page", ()=>{
    it("Checking hyperlinks for WOMEN", ()=> {
        cy.visit('/')
        cy.get('.sf-with-ul').contains('Women').click()
        cy.get('.cat-name').should('contain.text', 'Women')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Women"]').trigger('focus')
        cy.get('.sf-with-ul[title="Tops"]').click()
        cy.get('.cat-name').should('contain.text', 'Tops')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Women"]').trigger('focus')
        cy.get('[title="T-shirts"]').contains('T-shirts').click()
        cy.get('.cat-name').should('contain.text', 'T-shirts')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Women"]').trigger('focus')
        cy.get('[title="Blouses"]').contains('Blouses').click()
        cy.get('.cat-name').should('contain.text', 'Blouses')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Women"]').trigger('focus')
        cy.get('[title="Dresses"]').contains('Dresses').click()
        cy.get('.cat-name').should('contain.text', 'Dresses')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Women"]').trigger('focus')
        cy.get('[title="Casual Dresses"]').contains('Casual Dresses').click()
        cy.get('.cat-name').should('contain.text', 'Casual Dresses')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Women"]').trigger('focus')
        cy.get('[title="Evening Dresses"]').contains('Evening Dresses').click()
        cy.get('.cat-name').should('contain.text', 'Evening Dresses')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Women"]').trigger('focus')
        cy.get('[title="Summer Dresses"]').contains('Summer Dresses').click()
        cy.get('.cat-name').should('contain.text', 'Summer Dresses')
    })
    it("Checking hyperlinks for Dresses", ()=>{
        cy.visit('/')
        cy.get('.sf-with-ul').contains('Dresses').click({force: true})
        cy.get('.cat-name').should('contain.text', 'Dresses')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Dresses"]').contains('Dresses').trigger('focus', {force: true})
        cy.get('[title="Casual Dresses"]').contains('Casual Dresses').click()
        cy.get('.cat-name').should('contain.text', 'Casual Dresses')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Dresses"]').contains('Dresses').trigger('focus', {force: true})
        cy.get('[title="Evening Dresses"]').contains('Evening Dresses').click()
        cy.get('.cat-name').should('contain.text', 'Evening Dresses')
        cy.visit('/')
        cy.get('.sf-with-ul[title="Dresses"]').contains('Dresses').trigger('focus', {force: true})
        cy.get('[title="Summer Dresses"]').contains('Summer Dresses').click()
        cy.get('.cat-name').should('contain.text', 'Summer Dresses')

    })
    it("Checking hyperlinks for T-shirts", ()=>{
        cy.visit('/')
        cy.get('[title="T-shirts"]').contains('T-shirts').click({force: true})
        cy.get('.cat-name').should('contain.text', 'T-shirts')

    })
    it("Checking hyperlinks for Blog", ()=>{
        cy.visit('/')
        cy.get('[title="Blog"]').contains('Blog').should('have.attr', 'href').and('include', 'http://www.prestashop.com/blog/')
    })
})