/// <reference types="cypress" />

describe("E2E - Testing Main Page", ()=>{
    it("Checking hyperlinks for WOMEN", ()=> {
        cy.visit("/")
        cy.get("#block_top_menu > ul > li:nth-child(1) > a").click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Women')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(1) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li:nth-child(1) > ul > li:nth-child(1) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Tops')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(1) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li:nth-child(1) > ul > li:nth-child(1) > ul > li:nth-child(1) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'T-shirts')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(1) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li:nth-child(1) > ul > li:nth-child(1) > ul > li:nth-child(2) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Blouses')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(1) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li:nth-child(1) > ul > li:nth-child(2) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Dresses')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(1) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li:nth-child(1) > ul > li:nth-child(2) > ul > li:nth-child(1) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Casual Dresses')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(1) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li:nth-child(1) > ul > li:nth-child(2) > ul > li:nth-child(2) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Evening Dresses')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(1) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li:nth-child(1) > ul > li:nth-child(2) > ul > li:nth-child(3) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Summer Dresses')
    })
    it("Checking hyperlinks for Dresses", ()=>{
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(2) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Dresses')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(2) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li:nth-child(2) > ul > li:nth-child(1) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Casual Dresses')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(2) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li.sfHover > ul > li:nth-child(2) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Evening Dresses')
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(2) > a').trigger('focus')
        cy.get('#block_top_menu > ul > li.sfHover > ul > li:nth-child(3) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'Summer Dresses')

    })
    it("Checking hyperlinks for T-shirts", ()=>{
        cy.visit("/")
        cy.get('#block_top_menu > ul > li:nth-child(3) > a').click()
        cy.get('#center_column > div.content_scene_cat > div > div > span').should('contain.text', 'T-shirts')

    })
    it("Checking hyperlinks for Blog", ()=>{
        cy.visit("/")
        cy.get('a[title="Blog"]').should('have.attr', 'href', 'http://www.prestashop.com/blog/')
    })
})